apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: persona-brief-certificate
  namespace: persona-brief
spec:
  # Secret names are always required.
  secretName: persona-brief-tls
  dnsNames:
    - k8spro.dev
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
