apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  # Secret names are always required.
  secretName: "{{ .Values.certificate.secretName }}"
  dnsNames:
    - "{{ .Values.hostName }}"
  # Issuer references are always required.
  issuerRef:
    name: "{{ .Values.certificate.issuerRef.name }}"
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: "{{ .Values.certificate.issuerRef.kind }}"