apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: API_KEY
        - name: SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: SEARCH_ENGINE_ID
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: PROJECT_ID
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: LOCATION
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
