name: 'Build and Deploy to GKE'
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "app/**"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  LOCATION: ${{ secrets.LOCATION }}
  REPOSITORY: ${{ secrets.REPO_NAME }}
  IMAGE: ${{ secrets.IMAGE }}
  ZONE: ${{ secrets.ZONE }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  API_KEY: ${{ secrets.API_KEY }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
  HOST_NAME_URL: ${{ secrets.HOST_NAME_URL }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.GCP_SERVICE_ACCOUNT }}'

      - name: 'Authenticate Docker to Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev --quiet

      - name: 'Set up GKE credentials'
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.CLUSTER_NAME }}'
          location: '${{ env.ZONE }}'

      - name: 'Build and Push Docker Image'
        run: |
          DOCKER_TAG="${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          
          docker build --tag "$DOCKER_TAG" ./app
          
          docker push "$DOCKER_TAG"

      - name: 'Prepare Helm Values'
        run: |
          export REPO_NAME="${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}"
          export TAG="${{ github.sha }}"
          envsubst < ./k8s/values.template.yaml > ./k8s/app_chart/values.yaml

          
      - name: 'Setup Namespace'
        run: |
          kubectl config set-context --current --namespace "$NAMESPACE"
          helm list
          

      - name: 'Deploy with Helm'
        run: |
          helm upgrade --install persona-brief ./k8s/app_chart \
          --values ./k8s/app_chart/values.yaml --namespace "$NAMESPACE"
